services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    expose:
      - 8123
    ports:
      - 8123:8123
    volumes:
      - clickhousedata:/var/lib/clickhouse
      - clickhouseconfig:/etc/clickhouse-server
      
volumes:
  clickhousedata:
    driver: local
    driver_opts:
      device: ./clickhouse_data/
      o: bind
      type: none
  clickhouseconfig:
    driver: local
    driver_opts:
      device: ./clickhouse_config/
      o: bind
      type: none
