services:

  db:
    image: docker.arvancloud.ir/postgres
      #restart: always
    container_name: postgresql
    volumes:
      - postgresql-data-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
volumes:
  postgresql-data-vol:
    driver: local
    driver_opts:
      device: ./postgresql_data/
      o: bind
      type: none
