version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - clickhouse-network
  clickhouse01:
    image: clickhouse/clickhouse-server:23.7
    container_name: clickhouse01
    hostname: lx51
    networks:
      - clickhouse-network
    ports:
      - "127.0.0.1:8223:8123"
      - "127.0.0.1:9001:9001"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:23.7
    container_name: clickhouse02
    hostname: lx52
    networks:
      - clickhouse-network
    ports:
      - "127.0.0.1:8323:8123"
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:23.7
    container_name: clickhouse03
    hostname: lx53
    networks:
      - clickhouse-network
    ports:
      - "127.0.0.1:8423:8123"
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zookeeper
        #  clickhouse04:
        #    image: clickhouse/clickhouse-server:23.7
        #    container_name: clickhouse04
        #    hostname: clickhouse04
        #    networks:
        #      - clickhouse-network
        #    ports:
        #      - "127.0.0.1:8523:8123"
        #    volumes:
        #      - ${PWD}/clickhouse04:/etc/clickhouse-server
        #    depends_on:
        #      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
