version: '3.1'

services:
  n8n:
    image: n8nio/n8n
      #restart: always
    container_name: n8n
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIE=false
    expose:
      - 5678
volumes:
  n8n_data:
    driver: local
    driver_opts:
      device: ./n8n_data/
      o: bind
      type: none
