services:
  grafana:
    image: docker.arvancloud.ir/grafana/grafana
      #restart: always
    container_name: grafana
    volumes:
      - grafana-data-vol:/var/lib/grafana
    ports:
      - 3000:3000
volumes:
  grafana-data-vol:
    driver: local
    driver_opts:
      device: ./grafana_data/
      o: bind
      type: none
