version: '3.3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb_container
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 27017:27017
    expose:
    - 27017
    volumes:
      - mongodbdata:/var/lib/mongodb
      
volumes:
  mongodbdata:
    external: true
