services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo    
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodbdata:/var/lib/mongodb
      
volumes:
  mongodbdata:
    driver: local
    driver_opts:
      device: ./mongodb_data/
      o: bind
      type: none
 
