version: '3.3'

services:
  drill:
    image: apache/drill:latest
    stdin_open: true
    expose:
      - 8047
    ports:
      - 8047:8047
    volumes:
      - drilldata:/opt/drill/
      
volumes:
  drilldata:
    driver: local
    driver_opts:
      device: ./data/
      o: bind
      type: none

